version: '1'

services:
  postgres:
    image: postgres:latest
    environment:
     DATABASE_URL=$DATABASE_URL

  backend:
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
      