version: '3'

services:
  db:
    image: postgres:latest

    environment:
      - POSTGRES_DB=bookmark
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - DB_NAME=bookmark
    
    container_name: db
     
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  backend:
    build: .
    container_name: bookmark
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  pgdbdata: null
      