# Generated by Django 4.2.2 on 2023-08-15 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_header', models.CharField(max_length=100, verbose_name='Заголовок страницы')),
                ('page_description', models.CharField(max_length=255, verbose_name='Краткое описание страницы')),
                ('page_link', models.CharField(max_length=255, verbose_name='Ссылка на страницу')),
                ('type_of_link', models.CharField(choices=[('website', 'Website'), ('book', 'Book'), ('article', 'Article'), ('music', 'Music'), ('video', 'Video')], default='website', max_length=8, verbose_name='Тип ссылки')),
                ('preview', models.ImageField(upload_to='', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_title', models.CharField(max_length=120, verbose_name='Название коллекции')),
                ('collection_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена в')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkInCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookamrk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.bookmark', verbose_name='Закладка')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection', verbose_name='Коллекция')),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='collection',
            field=models.ManyToManyField(through='collection.BookmarkInCollection', to='collection.collection'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
